//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace PuraFruta.Models.ORMDataModel
{

    public partial class Customer : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fAddress;
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        string fCity;
        public string City
        {
            get { return fCity; }
            set { SetPropertyValue<string>(nameof(City), ref fCity, value); }
        }
        double fTotalOrdersAmount;
        public double TotalOrdersAmount
        {
            get { return fTotalOrdersAmount; }
            set { SetPropertyValue<double>(nameof(TotalOrdersAmount), ref fTotalOrdersAmount, value); }
        }
        Order fLastOrder;
        public Order LastOrder
        {
            get { return fLastOrder; }
            set { SetPropertyValue<Order>(nameof(LastOrder), ref fLastOrder, value); }
        }
    }

}
