//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace PuraFruta.Models.ORMDataModel
{

    public partial class FruitOrder : XPObject
    {
        Fruit fFruitPrice;
        public Fruit FruitPrice
        {
            get { return fFruitPrice; }
            set { SetPropertyValue<Fruit>(nameof(FruitPrice), ref fFruitPrice, value); }
        }
        decimal fAmount;
        public decimal Amount
        {
            get { return fAmount; }
            set { SetPropertyValue<decimal>(nameof(Amount), ref fAmount, value); }
        }
        double fTotalPrice;
        public double TotalPrice
        {
            get { return fTotalPrice; }
            set { SetPropertyValue<double>(nameof(TotalPrice), ref fTotalPrice, value); }
        }
        Order fAssignedOrder;
        [Association(@"FruitOrderReferencesOrder")]
        public Order AssignedOrder
        {
            get { return fAssignedOrder; }
            set { SetPropertyValue<Order>(nameof(AssignedOrder), ref fAssignedOrder, value); }
        }
    }

}
