//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace PuraFruta.Models.ORMDataModel
{

    public partial class Fruit : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fDescription;
        public string Description
        {
            get { return fDescription; }
            set { SetPropertyValue<string>(nameof(Description), ref fDescription, value); }
        }
        string fUnitMeasure;
        public string UnitMeasure
        {
            get { return fUnitMeasure; }
            set { SetPropertyValue<string>(nameof(UnitMeasure), ref fUnitMeasure, value); }
        }
        string fUnitPrice;
        public string UnitPrice
        {
            get { return fUnitPrice; }
            set { SetPropertyValue<string>(nameof(UnitPrice), ref fUnitPrice, value); }
        }
        string fDateInserted;
        public string DateInserted
        {
            get { return fDateInserted; }
            set { SetPropertyValue<string>(nameof(DateInserted), ref fDateInserted, value); }
        }
        string fDateLastStockInserted;
        public string DateLastStockInserted
        {
            get { return fDateLastStockInserted; }
            set { SetPropertyValue<string>(nameof(DateLastStockInserted), ref fDateLastStockInserted, value); }
        }
        double fStock;
        public double Stock
        {
            get { return fStock; }
            set { SetPropertyValue<double>(nameof(Stock), ref fStock, value); }
        }
    }

}
