//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace PuraFruta.Models.ORMDataModel
{

    public partial class Order : XPObject
    {
        string fDate;
        public string Date
        {
            get { return fDate; }
            set { SetPropertyValue<string>(nameof(Date), ref fDate, value); }
        }
        decimal fTotalPrice;
        public decimal TotalPrice
        {
            get { return fTotalPrice; }
            set { SetPropertyValue<decimal>(nameof(TotalPrice), ref fTotalPrice, value); }
        }
        Customer fCustomer;
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        [Association(@"FruitOrderReferencesOrder")]
        public XPCollection<FruitOrder> FruitOrders { get { return GetCollection<FruitOrder>(nameof(FruitOrders)); } }
    }

}
